name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
        sudo sh -c 'echo deb https://www.deb-multimedia.org sid main non-free > /etc/apt/sources.list.d/dm.list'
        sudo apt-get update -oAcquire::AllowInsecureRepositories=true
        sudo apt-get install -y haxe libstrophe-dev libopus-dev libdatachannel-dev
        haxelib setup ~/haxe
        haxelib --quiet install datetime
        haxelib --quiet install haxe-strings
        haxelib --quiet install hsluv
        haxelib --quiet install tink_http
        haxelib --quiet install sha
        haxelib --quiet install thenshim
        haxelib --quiet install hxcpp
        haxelib --quiet install hxtsdgen
        haxelib --quiet install utest

    - name: Tests
      run: make test

    - name: Build
      run: make
