name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y haxe libstrophe-dev
        haxelib setup ~/haxe
        haxelib install datetime
        haxelib install haxe-strings
        haxelib install hsluv
        haxelib install tink_http
        haxelib install sha
        haxelib install thenshim
        haxelib install hxcpp
        haxelib install hxtsdgen
        haxelib install utest

    - name: Tests
      run: make test

    - name: Build
      run: make
