name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y haxe libstrophe-dev
        haxelib /usr/share/haxe/lib
        sudo haxelib install datetime
        sudo haxelib install haxe-strings
        sudo haxelib install hsluv
        sudo haxelib install tink_http
        sudo haxelib install sha
        sudo haxelib install thenshim

    - name: Tests
      run: make test

    - name: Build
      run: make
